### ISSUE TITLE
Icon Data Downloading | icon_globe | No space left on device

### ISSUE THREAD

**Issue by Salphalor** [VACILT/PV_characteristics_ICON-NWP#4]
So i have cloned the icon_globe repo in ora. Then i created a fitting conda environment to be used by the bash/run script. 
So far i could handle the first obstacles. But i realized i changed some default configurations on ora.. 
Basically the problem was i could not activate an conda environment.
![Screenshot from 2021-11-29 22-35-48](https://user-images.githubusercontent.com/42503231/143956707-9d2d0b87-9ca1-497b-abc6-f4c087570552.png)
So i followed the suggestion to initialize a shell. 
I did 'conda init bash'  . Then after exiting the ssh and reconnecting i could activate the environment and install packages. But i realized now whenever i log into this specific account (ap1_09) the terminal showed (base) instead of ap1_09@ora at the beginning of each command line. I hope wont lead to confussions or errors. maybe i should ask Mr. Salzmann? 

Then i tried executing the run skript but ended up with errors, telling me the diskspace is full. Maybe the normal limit is overused, since the accounts are also used by other students, running ECHAM simulations?

Finally i switched to the account ap1_12, which i used during the seminar to keep my stuff togheter. On ap1_09 i deleted everything, but the conda shell remains default.
On ap1_12 i already run into disk space issues, trying to install the python requirements for icon_globe.

**Comment by kuchaale** [comment]
`source /opt/miniconda3/etc/profile.d/conda.sh` usually solves the problem.

**Comment by kuchaale** [comment]
If you @Salphalor encounter another bug, do not hesitate to open.
