### ISSUE TITLE
cronjob didnt work | datasize

### ISSUE THREAD

**Issue by Salphalor** [VACILT/PV_characteristics_ICON-NWP#5]
so today in the morning i didnt got an Email and when i checked there was no data for this date.. not sure why.

Also i wondered whether this file size is normal, i guess after some days one would run into diskspace issues.
![filesize](https://user-images.githubusercontent.com/42503231/145600568-a9de5fc8-1ab8-49c4-8848-d6f90bdf6b78.png)

I will check the preferences soon.

**Comment by Salphalor** [comment]
Okey i figured out that i had to activate the conda environment in the skript, so ill see over the weekend, if its working.

Another Problem occured which may lead to some variables not beeing downloaded such as the vertical wind. 
![Screenshot from 2021-12-10 17-08-20](https://user-images.githubusercontent.com/42503231/145605040-4d262136-343c-43f3-bb97-045336a31a11.png)

**Comment by Salphalor** [comment]
so the conda environment was just a part of thew issue, still no automatical downloads

**Comment by kuchaale** [comment]
Did you check the log files?

**Comment by kuchaale** [comment]
Can you try a simpler script to debug cron jobs at the server? [Here](https://www.baeldung.com/linux/cron-job-testing-debugging) are some suggestions on how to debug.

**Comment by Salphalor** [comment]
Oh okey this helped to get the log.

so what it says is that cdo command is not found.

**Comment by kuchaale** [comment]
Did you test cdo commands in your conda environment though?

**Comment by Salphalor** [comment]
Okey i installed cdo on conda and now it seems to be working. I am just abit confused, cause i thought conda installs just python packages and cdo is a different kind of software, outside the python environment. But good to know that this works also. cd ..
